### ISSUE TITLE
"Class private methods are not enabled" error when building the project

### ISSUE THREAD

**Issue by tniezurawski** [tracked-tools/tracked-built-ins#222]
I've just installed `tracked-built-ins` and got this error when doing `ember s`:

> Build Error (OneShot)
>
> -private/object.js: /Users/{PATH_EDITED}/my-project/-private/object.js: Class private methods are not enabled.
>   65 |
>   66 |   // @private
> 67 |   #readStorageFor(key) {
>      |   ^
>  68 |     let storage = this.#storages.get(key);
>  69 |
>  70 |     if (storage === undefined) {
>        in /var/folders/yn/ggs6qq9d0wj8q8pz_5kr94zm0000gn/T/broccoli-95128lZBubem9LmmO/out-02-funnel
>        at broccoli-persistent-filter:Babel > [Babel: tracked-built-ins] (Babel: tracked-built-ins)

This is my setup:

> $ ember -v
> ember-cli: 3.28.3
> node: 14.17.0
> os: darwin x64

I also use `embroider` with, I believe, latest possible versions:

> "@embroider/compat": "^0.47.1",
>    "@embroider/core": "^0.47.1",
>    "@embroider/webpack": "^0.47.1",

Any help? What should I do to make it working? 🙏

**Comment by xomaczar** [comment]
I'm seeing the same issue when using tracked-built-ins@2.0.0 and ember-source@4.0.1

**Comment by tniezurawski** [comment]
Thanks @xomaczar. I followed the issue and pinning `@babel/helper-create-class-features-plugin` to `7.14.6` unblocked me for now :+1:

```json
"resolutions": {
  "@babel/helper-create-class-features-plugin": "7.14.6"
},
```

**Comment by chriskrycho** [comment]
We fixed this upstream in ember-cli-babel; once that's released you should be able to update to the latest version of that and this issue will go away. Closing accordingly (though feel free to reopen if that doesn't resolve it).
