### ISSUE TITLE
`delete` doesn't trigger recomputation

### ISSUE THREAD

**Issue by boris-petrov** [tracked-tools/tracked-built-ins#27]
[Reproduction](https://github.com/boris-petrov/tracked-built-ins-bug).

Clicking the button sets a tracked object's property to something and clicking it a second time does a `delete`. That should hide some text that is shown and should log `undefined`. Neither happens. I think this is a bug.

**Comment by lifeart** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/deleteProperty should fix issue for objects

**Comment by boris-petrov** [comment]
@chriskrycho - now that I think about this, why did you mark this issue as closed? I keep looking at that PR and I see nothing related to it. You can see the two unmerged PRs - they add a `delete` handler to the Proxy - and I believe that's the only way to fix this issue.

**Comment by chriskrycho** [comment]
Just typo'd which issue it was supposed to resolve!
