### ISSUE TITLE
Convert to v2 addon

### ISSUE THREAD

**Issue by SergeAstapov** [tracked-tools/tracked-built-ins#274]
As this addon provides only run-time functionality hence it's the great candidate for v2 addon conversion.

This would require major release.

@chriskrycho any thoughts, concerns?

**Comment by chriskrycho** [comment]
As with tracked-tools/tracked-maps-and-sets#223, I'm strongly in favor and we can land it and cut a beta release, and then plan to do the actual next major in coordination with that.

An alternative approach I'd love your thoughts on: we could just… *not*… do the work on tracked-maps-and-sets for a standalone release, and leave it as-is, basically just sitting there with support for IE11, and fold its functionality into this single package, which will dramatically simplify ecosystem coordination.

---

(Related: if you want to write an RFC, I can mentor writing one to get the whole tracked-built-ins stack folded into a single package that we ship with the default blueprint etc.: it's very much needed and we discussed doing exactly that at a recent Framework Core meeting.)

**Comment by SergeAstapov** [comment]
> fold `tracked-maps-and-sets` functionality into this single package

@chriskrycho that totally makes sense to me as it definitely will help simplify maintenance.

@chriskrycho regarding RFC - I've already started working on it, will share draft by the end of this week.

**Comment by SergeAstapov** [comment]
Created https://github.com/tracked-tools/tracked-toolbox/issues/293 instead of this one as v2 addon format is just part of the major release.
