### ISSUE TITLE
TrackedArray.push dirties and consumes the collection tag

### ISSUE THREAD

**Issue by speigg** [tracked-tools/tracked-built-ins#29]
The `push` method dirties the collection tag, and subsequently does a `get` on the `length` property (since the `push()` method normally returns the length), which consumes the collection tag. This means that `push()` can't be called more than once without triggering this error: 

`Error: You attempted to update '(an unknown tag)', but it had already been used previously in the same computation.  Attempting to update a value after using it in a computation can cause logical errors, infinite revalidation bugs, and performance issues, and is not supported.`

Or, more generally, the tracked array can't be further modified after `push()` is called the first time.

**Comment by pzuraq** [comment]
hmm, yeah this seems like an annoying issue. I think we could get around it by binding `push` to the original array so it circumvents the proxy, like we do with the various getter functions.

**Comment by runspired** [comment]
I don't think any of the getter/setter methods need to consume or dirty the tag, that will happen naturally if the implementation is fixed such that access goes through the proxy for each cell.
