### ISSUE TITLE
Plan for v3 release

### ISSUE THREAD

**Issue by SergeAstapov** [tracked-tools/tracked-built-ins#293]
An outline of what I think needs to be done for a v3 release:

* [x] #320
* [x] #328
* [x] cut major v3.0.0

**Comment by chriskrycho** [comment]
This seems good. We also need to get better TS support and testing in place (#51). I'm working on that today!

**Comment by chriskrycho** [comment]
I also remembered what I just noted on tracked-tools/tracked-maps-and-sets#274: we want to integrate that library directly into this one. That will make the ecosystem coordination much easier, as we'll only need this library. (That is technically not a *blocker* for v3, though, and can in fact happen in a v2.x release, but I think we should do it *before* we do v3!)

**Comment by chriskrycho** [comment]
Updating on this: we don't actually need to make this an Embroider v2 addon as part of the breaking change; that can come in a 3.1 release or similar. Updating the tracking issue accordingly.

**Comment by SergeAstapov** [comment]
@chriskrycho v2 addon is breaking due to the fact that it requires the app (or an addon) have ember-auto-import@2 available.

hence technically, to make Embroider v2 addon in a 3.1 release or similar, we would need to include ember-auto-import@2 as dependency in v3 (like we did for ember-source v4).

**Comment by chriskrycho** [comment]
We already have it! 😉 I checked before adding that comment. In any case, though, you're correct that we need that, but *that* is the breaking change. Once that has been made, switching to Embroider v2 addon format will *not* be breaking.
