### ISSUE TITLE
Update tsconfig to match the standard blueprint

### ISSUE THREAD

**Issue by chriskrycho** [tracked-tools/tracked-built-ins#335]
Either:

- copy directly from ember-cli-typescript's blueprint

or:

- use `@tsconfig/ember` if tsconfig/bases#102 lands soon enough

**Comment by SergeAstapov** [comment]
let's do this after #332 lands to reduce conflicts churn :)

**Comment by chriskrycho** [comment]
We should be able to `yarn add -D @tsconfig/ember` and do `"extends": "@tsconfig/ember/tsconfig.json"` in the config starting tomorrow. (The blueprint on the Ember side will be updated to do the same.)
