### ISSUE TITLE
Newer method(s) missing from TrackedArray type

### ISSUE THREAD

**Issue by elwayman02** [tracked-tools/tracked-built-ins#416]
The types for TrackedArray don't include the newer (but fully supported) method [`findLast()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findLast) 

I *think* that means we just need to add it [here](https://github.com/tracked-tools/tracked-built-ins/blob/master/addon/src/-private/array.ts#L23), but not sure?

It may be worth doing a general review of all the built-ins to see what other methods have achieved full browser support since the initial implementation and ensuring those methods are properly accounted for since the built-ins are intended to have 1:1 functionality with their native counterparts.

**Comment by acorncom** [comment]
@elwayman02 do you happen to have time to put into this? There are various aspects to TrackedArray that could use some love based on looking at issues ...

**Comment by NullVoxPopuli** [comment]
do you have a reproduction? TrackedArray uses the same types as Array -- so this smells like a tsconfig configuration issue more than anything

**Comment by NullVoxPopuli** [comment]
https://www.typescriptlang.org/play/?target=99#code/JYWwDg9gTgLgBAbzgFSgQwMYGsCmATAQSnQE84BfOAMyghDgHIZ1t8BaAIwFdgAbGNsAB2AZwYBuAFCTeOeGmJoyAXjhCcAdxQtchRSQAUAbQCMAGgBMZgMwBdAJRTJC0gDoqwvABk0ImAaEuemUAPjUguABSOAt7IA 

yea, it works -- check your tsconfig.

Closing!
